### ISSUE TITLE
Add support for string escaping

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#2565]
Dark strings support newlines if you paste them in, but not if you type `\n`. Same with tabs.

We'd like to take existing strings and:
- if they contain a literal newline or tab character, display it as `\n` and `\t`
- if they contain a `\` followed by an `n`, show it as `\\n` (same for tab)
- these should be stored in the program as literal newlines/tab characters (there are many existing strings in existing programs, so keeping the format the same is important)
- investigate the user experience of typing these in the client - anything we can do better?
- the escapes to support are `\\`, `\n`, `\r`, `\t`, `\"`
- users have complained about being able to add a `"` at the end of a string, we should support that

**Comment by pingiun** [comment]
I think the straightforward solution here would introduce a lot of headache in a lot of areas. But let me write out what I think is the straightforward solution first.

Basically in the `toText` from `client/src/fluid/FluidToken.ml` you would do this:
```diff --git a/client/src/fluid/FluidToken.ml b/client/src/fluid/FluidToken.ml
index c3c0856db..2f9a0a506 100644
--- a/client/src/fluid/FluidToken.ml
+++ b/client/src/fluid/FluidToken.ml
@@ -443,13 +450,13 @@ let toText (t : t) : string =
   | TFloatFractional (_, f, _) ->
       f
   | TString (_, str, _) ->
-      "\"" ^ str ^ "\""
+      "\"" ^ showEscapes str ^ "\""
   | TStringMLStart (_, str, _, _) ->
-      "\"" ^ str
+      "\"" ^ showEscapes str
   | TStringMLMiddle (_, str, _, _) ->
-      str
+      showEscapes str
   | TStringMLEnd (_, str, _, _) ->
-      str ^ "\""
+      showEscapes str ^ "\""
   | TTrue _ ->
       "true"
   | TFalse _ ->
```

Which makes it so multiline strings are shown like this in the editor:
<img width="530" alt="image" src="https://user-images.githubusercontent.com/1576660/86537385-f3343400-beee-11ea-8149-d593b03737e0.png">

The problem is that one character in the source now shows as two characters in the editor, and the editor is not really built for that. Moving the cursor over the `\n` works okay, but pressing backspace after the `\n` will delete one character after the character you wanted to delete. It seems that changing this behaviour would require a lot of changes in the editor.

Another option might be to display a ␊ character in the string, as this is a single unicode character and should work fine. I don't think this is the best solution because the user might want to type the actual  ␊ character in their string.

One more option I can think of is replacing the `string` in `TString of ID.t * string * parentBlockID option` to something else such that proper handling of special characters is embedded in the type.

**Comment by pbiggar** [comment]
Thanks for looking into this!

> The problem is that one character in the source now shows as two characters in the editor, and the editor is not really built for that. Moving the cursor over the \n works okay, but pressing backspace after the \n will delete one character after the character you wanted to delete. It seems that changing this behaviour would require a lot of changes in the editor.

This seems like a promising area to look into: my guess is that there aren't all that many places that this affects; possibly just backspace and delete? Though there is the question of how to represent/display just a `\` by itself. Perhaps `TString` etc should be something like `TString of string_part list` where `type string_part = | StringNewline | String of string | StringEscapePartial` etc?

> Another option might be to display a ␊ character in the string, as this is a single unicode character and should work fine. I don't think this is the best solution because the user might want to type the actual ␊ character in their string.

We could use an icon here instead of an LF. I kinda like this solution, though we'd need to find a way to communicate to the user how to enter a newline (eg press `\` to go into another mode?).

> One more option I can think of is replacing the string in TString of ID.t * string * parentBlockID option to something else such that proper handling of special characters is embedded in the type.

I'm not sure exactly what this means, but I like the idea of properly representing this in the type (at least in the tokens).

**Comment by pbiggar** [comment]
Going to close this in favor of #3433, which addresses the same problem more holistically.
