### ISSUE TITLE
Make the Dark repo work on Windows

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#2653]
Folks have tried and failed to run the Dark dev container on Windows.

Write a guide for windows users, and make any code changes necessary to make it a good experience.

**Comment by kberridge** [comment]
I got Dark running on Windows in WSL2 (Windows Subsystem for Linux) this weekend.  Here's some information on setting it up.

- It does NOT work on WSL1, because docker only works in WSL2
- WSL2 is available starting in Windows 10 Version 2004, which is rolling out now
- Instructions on setting up WSL2 are here: https://docs.microsoft.com/en-us/windows/wsl/install-win10#update-to-wsl-2
- Instructions on setting up Docker for WSL2 are here: https://docs.docker.com/docker-for-windows/wsl/
- After that, following the instructions in Dark's README works fine with no additional steps or modifications needed

**Comment by pbiggar** [comment]
Awesome, thanks! Can you add these as notes in the README?

**Comment by pbiggar** [comment]
This looks like it's working
