### ISSUE TITLE
We shouldn't expect bodies to be unicode strings

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3424]
We automatically convert HTTP bodies into strings, even if it's not valid Unicode. This means users can't send bytes.

We should instead have a collection of middlewares, acting on the low-level HTTP stuff (verbs, headers and byte bodies, returning status code, headers and byte bodies). One of those middlewares would be to just get bytes in raw.

The `raw` value on http middleware is similarly a string but it should be bytes, or i guess it would depend on the middleware.

**Comment by StachuDotNet** [comment]
I'm starting to look at this issue as it relates to #4259. While I'm comfortable starting alone and re-exploring the existing code, any additional thoughts here in the meantime would be appreciated.

**Comment by pbiggar** [comment]
I would start with creating a new version of HttpMiddlewareV0 zero that does nothing except send and receive bytes and calls the dark handler with a `DBytes` value. The challenge then is how do we allow users to choose that middleware instead of the default one.

**Comment by StachuDotNet** [comment]
Progress check / brain-dump:

So far, I've
- met with Paul to discuss direction, a bit of UX
- studied `BwdServer`, `HttpMiddleware.__V0` modules, and how these interact
- made some local refactorings to make it more obvious in `BwdServer.Server.fs` where the "middleware" starts and ends
- dug into the ApiServer side of things - we offer 'sample traces' to users when they're creating a new HTTP handler. Right now there's one static `request` record dumped into context, much of which would be irrelevant to users using this new thin middle

Here's what I'm thinking:
- I need to tidy my local refactorings, and create a thin PR that's a no-op but (imo) improves legibility
- the `HttpMiddleware.__V0` modules are of inconsistent shapes, and expose multiple functions. Overall, it feels like the seam between "middleware" and "bwdserver" is really muddy. I'd like to turn these "Middlewares" into functions (rather than modules exposing multiple functions) with a consistent input/output
- in fact, much of what's in `runDarkHandler` should be moved into "middleware space"?
- we need to adjust ApiServer trace-loading to pull from the middleware stack of a relevant HTTP handler
- as for the "right place" to record the `middleware`s of a specific Http handler, I'm tempted to change the `ProgramTypes.Handler.Spec.Http` to have a new component: `middlewares: middleware list`, where `middleware` is ... something. Maybe `{ id: id }`, whose ID may also be found in a dictionary that ApiServer and BwdServer respects
- I still like the UX intentions we discussed yesterday. We can keep it thin for now (just a simple box on the top "HTTP" bar, allowing the user to switch (probably with a warning that it may break their code)

So, my next intentions are to
- [ ] get some feedback from Paul
- [ ] tidy the local minor refactorings / commentary and get it into a no-op PR
- [ ] follow up with a PR that refactors the existing "middlewares" to have a common shape (input/output)
  - the one wrinkle in this that I see is the `options` 
- [ ] refactor such that the "sample" trace information can be fed partially by which Http Handler is chosen
  `ApiServer` will likely reference `HttpMiddleware` with this?
- [ ] actually implement the new bytes-only middleware

**Comment by StachuDotNet** [comment]
as a misc note: the idea of writing middlewares in Dark (rather than F#) sooner than later is actually seeming realistic.
Almost tempted to have the mentioned "thin bytes-friendly middleware" be in Dark, leaving the existing middleware being the only one that stays in F#-land.

**Comment by StachuDotNet** [comment]
To be more clear: all of [this](https://github.com/darklang/dark/blob/6af54726fcf429768f0e05f656684b868d42cf46/fsharp-backend/src/BwdServer/Server.fs#L330-L404), except for the `moreThanOneHandlerResponse` bit, feels like it should be in `HttpMiddlewareV0`.

**Comment by StachuDotNet** [comment]
Once an HTTP handler may choose which middlewares to apply in an HTTP handler, and a 404 comes in, what should happen?

Right now, you click on the 404 in your sidebar it it automatically creates an HTTP handler. I suppose we'd need another step, to choose the 'correct' middleware for the request? Or maybe the 'middleware' slot of the HTTP top bar is blank, and the user has to choose it, likely after taking a peek at the trace.

**Comment by StachuDotNet** [comment]
(likely wrong) it's starting to feel like I want an "input middleware" type and an "output middleware" type

**Comment by StachuDotNet** [comment]
Once middlewares are written in Dark, `RealExe.executeHandler` is exposed as a StdLib function, versioned per Interpreter version?

**Comment by pbiggar** [comment]
> Once an HTTP handler may choose which middlewares to apply in an HTTP handler, and a 404 comes in, what should happen?
> 
> Right now, you click on the 404 in your sidebar it it automatically creates an HTTP handler. I suppose we'd need another step, to choose the 'correct' middleware for the request? Or maybe the 'middleware' slot of the HTTP top bar is blank, and the user has to choose it, likely after taking a peek at the trace.

Another good reason to store the trace as bytes!

**Comment by pbiggar** [comment]
> Once middlewares are written in Dark, `RealExe.executeHandler` (or some part of it) is exposed as a StdLib function, versioned per Interpreter version?

I wouldn't expose that directly. The point of functional middleware stacks is that they're all functions that wrap other functions and call "the next thing". The final "next thing" is running the AST and so we should have an adapter for that. Put another way, our stack should take a middleware and adapt to calling it appropriately.

**Comment by StachuDotNet** [comment]
Closing this - please see https://github.com/darklang/dark/discussions/4325 for more discussion (especially the google doc linked there)
