### ISSUE TITLE
Fuzz all pure functions

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#3556]
Mark LibJwt, x509 and crypto functions as ImpurePreviewable to run in the fuzzer

**Comment by StachuDotNet** [comment]
Just to make sure I understand correctly, would this be an appropriate rephrase?
"Fuzztest LibJwt, x509 and crypto functions. You'll need to mark them as ImpurePreviewable to run in the fuzzer"?

**Comment by StachuDotNet** [comment]
[Here](https://dynalist.io/d/xYMggOIEkXlxNh01DVXlNG4_#collapse&theme=dark)'s an analysis of the Dark fns, noting which ones can/can't be fuzztested.

I gathered the list by writing a [a variant of `DarkInternal::allFunctions`](https://gist.github.com/StachuDotNet/3b0ef98e09d71fac3e228dd8ab58592e) locally which includes `Previewable` status, and manipulating the resultant JSON into the Dynalist doc, organizing fns where they seemed appropriate.

Some notes:
- I assume `toForm` should be ignored, as it's marked as for demo only
- `Date::today` is currently marked as `Pure` - I'm planning as marking this as `Impure`
- while _most_ of `StaticAssets` can't be fuzztested, several fns (`StaticAssets::baseUrlFor`, `StaticAssets::fetch`, `StaticAssets::urlFor`) should be fuzz-testable w/r/t ocaml interop, at least. Would those be appropriate to be marked as `ImpurePreviewable`?
- I haven't yet tested `X509::pemCertificatePublicKey`
- I'm still a bit confused why some functions are `ImpurePreviewable` rather than `Pure` (e.g. `Crypto::md5`); does `ImpurePreviewable` really mean "pure, but let's save it because it's a bit costly?" or am I misinterpreting?

If there are any fns in that document out of place, please let me know as I'm working my way through them.

**Comment by pbiggar** [comment]
> I'm still a bit confused why some functions are ImpurePreviewable rather than Pure (e.g. Crypto::md5); does ImpurePreviewable really mean "pure, but let's save it because it's a bit costly?" or am I misinterpreting?

"Pure" doesn't actually mean pure, it means "this can be run in the editor via js_of_ocaml". Some things were impure in the OCaml version as they were not runnable in the editor, mostly because of their use of C/native bindings.

"ImpurePreviewable" means "this can only run on the server but is actually pure" (eg `Crypto::md5`) or "you can safely run this without side-effects, but it is not pure" (eg `Date::now`).

**Comment by pbiggar** [comment]
> I gathered the list by writing a [a variant of `DarkInternal::allFunctions`](https://gist.github.com/StachuDotNet/3b0ef98e09d71fac3e228dd8ab58592e) locally which includes `Previewable` status (and doesn't exclude deprecated fns), and manipulating the resultant JSON into the Dynalist doc, organizing fns where they seemed appropriate.

These look right.

The DB ones could possibly be fuzztested:
- db::keys, db::schema etc could be fuzzed
- db::query etc could possibly be fuzzed, unsure?
- db::set/update could probably be fuzzed to see what's in the DB after

However, probably a lower priority than other stuff.

 
> Some notes:
> 
> * I assume `toForm` should be ignored, as it's marked as for demo only

Agreed.

> * `Date::today` is currently marked as `Pure` - I'm planning as marking this as `Impure`
> * String.htmlEscape is currently `Impore` - I believe it should be `Pure`

These should remain the same as OCaml until we've removed OCaml, so I'd add a CLEANUP comment to them instead.

If you're using "change them to `Pure`" to mean "test them as if they are pure", then yes, I agree.


> * while _most_ of `StaticAssets` can't be fuzztested, several fns (`StaticAssets::baseUrlFor`, `StaticAssets::fetch`, `StaticAssets::urlFor`) should be fuzz-testable w/r/t ocaml interop, at least. Would those be appropriate to be marked as `ImpurePreviewable`?

Only if it doesn't change their behaviour with respect to OCaml. Otherwise I'd add a CLEANUP to do it.

> * I haven't yet tested `X509::pemCertificatePublicKey` but understand it can be fuzztested; currently sitting in the 'unorganized' section at the bottom

**Comment by StachuDotNet** [comment]
Closing stale PR #3654 now, but wanted to extract two threads/todos so I don't forget:
- [JWT testing follow-up](https://github.com/darklang/dark/pull/3654#discussion_r843396933)
- [allowing Incompletes](https://github.com/darklang/dark/pull/3654#discussion_r843395327)

**Comment by pbiggar** [comment]
Should we declare this done?

**Comment by StachuDotNet** [comment]
Yeah I'd say so. Always more fuzztesting to do, but separate from this specific scope.
