### ISSUE TITLE
Some FuzzTests aren't clearing their canvases

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#3706]
Discovery found [here](https://github.com/darklang/dark/issues/3689#issuecomment-1100260392_). Known to be an issue at least for `executepurefunctions` and `bytes-to-string` fuzztests, but I see others as well.

I've been running FuzzTests a lot recently. Apparently I locally have 100k canvases of the form `test-executepurefunctions-[random]` right now.

We can resolve this by either clearing the canvases via code, or extract/re-use logic in the `integration-tests/clear-db.sh` script.

If going the latter route:
- [ ] extract test-canvas-deletion logic from `clear-db.sh` into a new script (`clear-test-canvases.sh`)
- [ ] edit that^ script to either:
  - (ideally) handle _many_ tests (right now it fails for more than 143 test canvases)
  - (good enough for now) provide commentary of how to hackily deal with such
- [ ] clear test canvases as part of fuzztest execution
  calling `clear-test-canvases` as part of `run-fsharp-fuzzer` should be fine for now

**Comment by StachuDotNet** [comment]
Misc. idea: when a round of tests is complete, run one final test to ensure there aren't any `test-` canvases hanging around, to ensure tests have cleaned up after themselves properly.

**Comment by pbiggar** [comment]
> idea: when a round of tests is complete, run one final test to ensure there aren't any `test-` canvases hanging around, to ensure tests have cleaned up after themselves properly.

Leaving canvases around is desirable as it allows us to inspect them afterwards. Though test canvases are expected to be in the testdb database.

**Comment by StachuDotNet** [comment]
Aha, that's fair! So, #3504 is the focus here, and this can be closed?

**Comment by pbiggar** [comment]
Sort of.

Some context:
- integration tests are supposed to run on the `devdb` DB, so you can look at the canvas with your browser if it fails. That's why clear-db only clears `test-` canvases
- non-integration tests are supposed to be run on the `testdb` DB. That's intended to be cleared on each new run of tests, and can be cleared with a simple `dropdb`
- ApiServer.Tests also operates on `devdb`. This is by-design, as we want to test do we get the same values from the ocaml server as we do on ApiServer. However, once we've removed the ocaml server, all the ApiServer tests will need to change in some form.

So perhaps the problem here is that the fuzzer is running on `devdb` instead of the `testdb`? If it was on testdb, we could clear it with a simple dropdb like we do in [run-fsharp-tests](https://github.com/darklang/dark/blob/8300dda26901dbeb41f98d935d896cecbf920ea8/scripts/run-fsharp-tests#L46).

**Comment by pbiggar** [comment]
We don't have fuzztests anymore.
