### ISSUE TITLE
Improve integration test perf, esp. in CI

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#3873]
Load Blazor only once (per worker) in integration tests, to reduce runtime.

Also, use parallel playwright workers.

See https://github.com/darklang/dark/projects/1#card-79650290 for maxconcurrentconnections in ApiServer

**Comment by pbiggar** [comment]
I wouldn't say I'm satisfied with per as it's still the longest step on our CI. But, I'm not sure that the context of this issue is helpful, as we probably actually want to move to multi machines again instead.

Happy to call this done, and wait until we're sufficiently annoyed by CI performance for this to come to the front.
