### ISSUE TITLE
Twitter sample canvas

### ISSUE THREAD

**Issue by Diederikjh** [darklang/dark#4320]
With lots of thanks to @jonathan-laurent for [starting this off originally about a year ago](https://darkcommunity.slack.com/archives/CNTCWD6MP/p1630010249005400).  I'd like to submit [my canvas for a starter canvas for sending tweets to the Twitter API](https://darklang.com/a/diederik-twitter-example).

Notes about the developer account on twitter side:  It needs to have "elevated" permissions, and the access tokens that are generated needs to be with read and write permissions.

I did test the `GET` verb once, but not as much as the `POST` one. 

Adding the correct values for the account key and access tokens should get this canvas working.  Just please add them to your secrets in stead of the variables it is in at the moment.

Thanks

**Comment by pbiggar** [comment]
Amazing, thank you! We'll get this ported over soon.

**Comment by StachuDotNet** [comment]
What's involved here, @pbiggar?

Clone the canvas into the `sample` org? Manually review, copy, and paste into a new `sample` canvas?

**Comment by pbiggar** [comment]
Yes, exactly.

**Comment by StachuDotNet** [comment]
Which of those is correct? Is there full-fledged canvas-cloning that's available, or is this a manual effort?

I believe the latter is the case, but I've seen bits of code around canvas-cloning, which is why I ask.

**Comment by pbiggar** [comment]
Oh right. Yes, it's the second.

**Comment by StachuDotNet** [comment]
The code is all set up in a sample canvas for twitter auth (https://darklang.com/a/sample-twitter-auth), but there are a bunch of hoops to jump through.  One of the hoops was to set up a twitter account, then sign up through the dev portal. I did so using a variant of my darklang email, figuring it'd just take a minute and be used for this one-off thing.

In order to use oauth 1.0, you need to go through this form: https://developer.twitter.com/en/docs/twitter-ads-api/apply

Which doesn't _feel_ relevant, but apparently it's the thing to do.

Anyway - it asks a bunch of questions, all which have unknown importance, but there are a lot of "agreements" to agree to that I'm not immediately comfortable just clicking "OK" on without chatting first.

What should I do from here?
- just click the agreements (you're not worried of something dumb)
- let you create an account, probably with the official darklang twitter account
- go through it together for a few minutes

Once we've gone through this step, I think it should just be a few minutes to get the canvas working.

That said, it'd be nice to ship this with some.. other advice. Twitter's documentation of this is really rough. I've started to add some 'docs' in the REPL.

**Comment by StachuDotNet** [comment]
If you go to that canvas, then to the (only) REPL and play it, you'll see their HTTP response describing the elevated privileges needed.

**Comment by StachuDotNet** [comment]
@pbiggar gentle reminder - what do you think? I think creating an official twitter dev account under the Dark twitter login probably makes the most sense here.

**Comment by pbiggar** [comment]
One used only for the sample canvas I assume?

**Comment by StachuDotNet** [comment]
For now, yes. (Maybe some day we use the dev account for some other twitter integration?)

**Comment by StachuDotNet** [comment]
I'm not sure - can check in a bit.
In any case, 'just showing code' is probably enough to call this ticket done?

I'd just like to add an `/about` route that returns some notes about how to use twitter auth - copying details from this thread and from the slack thread.

**Comment by pbiggar** [comment]
Yeah, that seems good.

If we did in the future wants to allow people to tweet directly from the canvas, we could add features to ensure secrets don't leak when doing that. But that's in the "public canvas" project, which is definitely not a blocker on calling this done.

**Comment by StachuDotNet** [comment]
I updated the sample canvas - could you please [take a look]() and let me know what else you think needs to be done before we 'release' this and call it done for now? https://darklang.com/a/sample-twitter-auth

**Comment by pbiggar** [comment]
Looks good! I would say the remaining thing would be to add it to https://docs.darklang.com/reference/sample-canvases

**Comment by StachuDotNet** [comment]
Thank you @Diederikjh - the cloned sample canvas is now on the above-noted link!

**Comment by Diederikjh** [comment]
Thanks all for getting this one the sample page - it feels good to help out.

One small note (sorry, I only got time to read through the sample canvas now).  I think the placeholder string on the line `let TWITTER_CONSUMER_KEY = "YOUR_TWITTER_API_SECRET"`  needs maybe read `TWITTER_CONSUMER_KEY = "YOUR_TWITTER_API_KEY"` as this is what it is called on the Twitter developer portal.  It could cause confusion maybe?

Otherwise it looks very good. Thanks

**Comment by StachuDotNet** [comment]
I've adjusted accordingly - thanks!
