### ISSUE TITLE
UUIDs not appearing correctly in list maps

### ISSUE THREAD

**Issue by sanderjson** [darklang/dark#4400]
[BUG][UI]

I discussed this issue before in Slack, and I believe the result was “works, just not updated correctly in the trace”.  

I find this issue makes it difficult to debug my program.

![image](https://user-images.githubusercontent.com/20689537/185294719-8700b8e8-ba68-4dd8-b47f-e044fc313abe.png)

**Comment by sanderjson** [comment]
This is more than a visual issue. The following code will fail. The `Dict:FromList` is reading duplicate entries for a key.

```
let data = {
             a : 123
             b : false
           }
let list = [data,data,data]
let test_prep = list
                |>List::map
                    \val -> Uuid::generate
                            |>toString
                            |>List::singleton
                            |>List::append val
                                           |>List::singleton
let test_check_uuid = test_prep
                      |>List::map \val -> val
                                          |>List::getAtv1 0
let test = test_prep
           |>Dict::fromList
test
```
<img width="781" alt="image" src="https://user-images.githubusercontent.com/20689537/195243724-215afa3b-3b2d-46de-bbdd-6a214c5e2df6.png">

**Comment by pbiggar** [comment]
In traces at the moment, impure functions such as `Uuid::generate` only have one value stored per function (even if called in loops or nested loops). So that value propagates everywhere when viewing the trace. If you were to run this in a HTTP handler in production, you would get the expected results.

> https://paul.builtwithdark.com/sanders-uuid-example

```
[
  [
    "a254dc54-0a65-4b3f-a8dd-aab8ba656282",
    {
      "a": 123,
      "b": false
    }
  ],
  [
    "3ef07ca3-e484-430a-9636-30dbc7e68969",
    {
      "a": 123,
      "b": false
    }
  ],
  [
    "87976031-25ec-4c9e-8e75-717908da50de",
    {
      "a": 123,
      "b": false
    }
  ]
]
```


That said, it's really time we fixed this properly. I'll bump this up the priority list of things to work on next - it actually coincides with some other work I wanted to do on traces.

**Comment by sanderjson** [comment]
Thanks!

It is failing in a production HTTP handler for me  because I can not call `Dict::get` on a record that doesn not exist within the trace. I have a work around in mind so no problem!
