### ISSUE TITLE
Rebrand 'patterns' as 'match patterns'

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#4489]
This is in preparation for #3402, where we will define and use 'let patterns'.

Generally throughout our codebase, the aim here is to make several universal renames to prevent confusion between 'let patterns' and 'match patterns':
- "Pattern" -> "MatchPattern"
  (e.g. `FluidPattern` -> `FluidMatchPattern`)
  these naming conventions are not currently serialized anywhere AFAIK.
- along with the above, update the prefixes used to name PT and RT pattern cases
  (e.g. `PString` -> `MPString`)
  these conventions _are_ serialized (to json) for client/server communication, for at least PTs (and maybe RTs?)

This rename is needed within each of `fsharp-backend` and `client`, and we need to ensure a smooth/safe transition between these naming conventions. We do not expect any issues in data within our DB, so the risk is only within API communication, as the front-end may be 'behind' the backend.

#4487 has started this effort, by completing this rebranding across the `client` codebase. It also prepares the PT and RT decoders to handle `MPString`-like match pattern cases.

From this point, I expect a few steps:
1. update backend minimally to decode `MPString`-style match pattern case serializations from `client` successfully
2. wait until users' clients are 'caught up' (no one is working on an old/incompatible client version
3. update backend _generally_ to rebrand 'patterns' as 'match patterns'
4. remove compatibility with `PString` in both backend and client, now that things have settled

(steps 2 and 3 may not have a dependency?)

**Comment by pbiggar** [comment]
ClientTypes exist because we don't want to expose RuntimeTypes to the API - we want the freedom to change Runtime types as appropriate for the actual runtime of the language. (Confusingly, the client typically uses ProgramTypes everywhere, and the only place it uses RuntimeTypes is for Dval's DLambda expr field).

ProgramTypes are really supposed to be the API type. They're not executed and they're not binary serialized either, but they act as an intermediate phase between all of these.

So I think you want to convert ProgramTypes to the new names, and add an intermediate layer between it and the client for now. It's fine to leave it in, and we'll need it again in the future no doubt.

To avoid future confusion, perhaps the Dval/Expr  portion of ClientTypes should be ClientRuntimeTypes and the new thing should be APIProgramTypes? Or probably not exactly that but something along those lines?

Does that help?

**Comment by StachuDotNet** [comment]
That helps, thanks! (currently on another task but will circle back and potentially have follow-ups)
