### ISSUE TITLE
Setting nested value in dictionary (feature request)

### ISSUE THREAD

**Issue by sanderjson** [darklang/dark#4495]
Editing nested objects within a dict feels overly complicated. Perhaps there is a more intuitive way. For example consider the process for editing the `prop three` values here. Perhaps this is a discussion?

```
let data = {
             _this : {
                       prop_one : false
                       prop_two : "abcs"
                       prop_three : {
                                      a : false
                                      b : false
                                    }
                     }
             more_stuff : []
             more_stuff_2 : {}
           }
let my_list = [data,data,data]
my_list
|>List::map
    \val -> let _this_update = val._this
                               |>Dict::set "prop_one" true
            Dict::set val "_this" _this_update
```

<img width="664" alt="image" src="https://user-images.githubusercontent.com/20689537/192079190-1b0a517a-21b6-402d-b113-e1d65b0cb2d3.png">

**Comment by pbiggar** [comment]
Thanks for the code. This looks like you're using dicts as records, so I guess the right solution will be syntactic rather than function based.

The standard way to do this in functional languages is something like:

```
{ ...val, _this: { ...val.this, prop_one: true } }
```

Which is pretty bad when compared to imperartive languages where you can do:

```
val._this.prop_one = true
```

Ideally, I'd like to find something as simple as the imperative approach, but that feels functional.

Some ideas:
```
val with _this.prop_one: true
```

```
{ ...val, _this.prop_one: true } 
```

**Comment by pbiggar** [comment]
Excellent resources, thank you for including them. I would add that Darklang currently only has dicts, but that everyone uses them as records. I plan to resolve this at some point, hopefully soon.
