### ISSUE TITLE
Not able to access variable within List::map despite trace showing value is processed

### ISSUE THREAD

**Issue by sanderjson** [darklang/dark#4496]
Have not created a REPL reproduction. Please see attached image.

The variable "artifacts_in_this_route" is not accessible within the list map despite being declared above (and successfully retrieving data).

<img width="874" alt="image" src="https://user-images.githubusercontent.com/20689537/192108554-427524a3-85eb-4b0e-b596-4082ac0ca419.png">

**Comment by sanderjson** [comment]
SImilar issue here. The "my_value" variable is not accessible from within the map despite showing a value in the trace (cursor hover).

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/20689537/192109796-687bafd5-eba1-48d4-af4b-506863795db7.png">

Created a reproduction REPL (below). Appears to work fine.

```
let my_data = ["key",{
                       prop_one : [1,2,3]
                       prop_two : false
                     }]
let my_list = [my_data,my_data,my_data]
my_list
|>List::map
    \val -> let my_key = val
                         |>List::getAtv1 0
            let my_value = val
                           |>List::getAtv1 1
            {}
            |>Dict::set my_key my_value
```

<img width="626" alt="image" src="https://user-images.githubusercontent.com/20689537/192109849-068f3947-3028-492e-9412-ab75f6ce63ee.png">

**Comment by pbiggar** [comment]
Thanks for reporting! This is a known issue here we don't track multiple values for different iterations of a trace. Obviously we should

**Comment by sanderjson** [comment]
Are you suggesting that one value of the iteration may have caused an error and therefore the value is unaccessible genarally? If so why does replacing the value with its equivilent code "fix" the issue? (above)

Changed `Dict::set my_key my_value` to `Dict::set my_key List::getAt val 1`

**Comment by pbiggar** [comment]
My apologies, I misunderstood the issue.

I've seen something like this before, and II suspect the issue is that the editor put the pipe around the wrong expression. You wanted

```
(let my_value = ...
 {} |> Dict::set my_value)
```

but you possibly got

```
(let my_value = ...
 {}) |> Dict::set ___ // my_value is out of scope
```

So the solution for this would be to highlight what the pipe is actually piping, and probably also to look at how pipes initially wrap other expressions.

**Comment by sanderjson** [comment]
I have since refactored this code to avoid this case, but revisitng here to close this issue.

Looking back over the screenshot I do not see or _understand_ the issue you are referencing.  Comparing image 1 to image 2 (below). Is there a difference in scope? Should this be obvious from the indentation?

I am also piping into the list during variable declaration but this shouldn't have an effect.

![image](https://user-images.githubusercontent.com/20689537/192792735-d34b8eb4-d04c-4cdb-92f9-76d30c5f9c61.png)


![image](https://user-images.githubusercontent.com/20689537/192792680-bbfd3235-79f3-4c6a-b247-d301ffb0f40f.png)

**Comment by pbiggar** [comment]
You're right that it's not visible from the code, which is a big issue. One solution might be to put parentheses around the piped expression when it's not the obvious one.

I'll try to explain the issue again:

A `let` expression has the following components:
- lhs: the variable name ("left-hand side")
- rhs: the value of the variable ("right hand side")
- body: another expression, for which the `lhs` variable is in scope

The `lhs` variable is only in scope in the body, not in expressions that follow this one.

So in this expression:

```
(let my_value = ...
 {}) |> Dict::set ___ // my_value is out of scope
```

`my_value` is only in scope within the parentheses, and so no longer in scope for the `Dict::set`. That is, the `let` is fully executed before the pipe. `my_value` is only available in the scope of `body` which is `{}`

But the real problem is that this isn't what you were trying to do. You were presumably trying to create this:


```
(let my_value = ...
 {} |> Dict::set my_value)
```

In this expression, the body of the `let` is `{} |> Dict::set my_value`. Since the pipe is in the body of the let, `my_value` is in scope.

So the bug here is that the editor put the pipe in wrong. And a further bug is there was no visual indication that this was the case.

Does that explain what's happening better?

**Comment by sanderjson** [comment]
This is a great explanation thank you. Order of operations is important! 

> **So the bug here is that the editor put the pipe in wrong.** And a further bug is there was no visual indication that this was the case.

To paraphrase and confirm my understanding — Referencing the two images below is it fair to say that slightly different user input within the editor resulted is a different function scope despite the same user intent? And furthermore, this difference should be made clear to the user? 

Happy to close on **user error** and open _two_ separate issues if this is correct.

![image](https://user-images.githubusercontent.com/20689537/193086611-272e7256-387e-44ac-a54e-92771b53f632.png)

![image](https://user-images.githubusercontent.com/20689537/193085067-cda82a3a-ca06-4995-9e02-a284b8ba7735.png)

**Comment by pbiggar** [comment]
Yeah, sounds great, thanks!

**Comment by StachuDotNet** [comment]
> You're right that it's not visible from the code, which is a big issue. One solution might be to put parentheses around the piped expression when it's not the obvious one.

In the meantime, @sanderjson you might benefit from inspecting the in the in-Editor contributor debugging tools. Enable like this (feel free to ignore the bits about tuples):
![image](https://user-images.githubusercontent.com/906686/193591165-a036a55d-964f-4c0c-8637-b992484f637c.png)

This isn't a great solution long-term, but may help diagnose/communicate some awkward editor issues like this in the meantime.
