### ISSUE TITLE
make 'debugger' queryParam more obvious, or remove it?

### ISSUE THREAD

**Issue by StachuDotNet** [darklang/dark#4567]
I saw that this was a thing, but haven't looked into it more. Should it be a contributor setting?

**Comment by pbiggar** [comment]
Unsure.

It doesn't do a good job - it's a reimplementation of Elm's debugger from bucklescript-tea that never got much love.

It needs to be in a queryParam because it's needed at loadtime. We could do it similar to a tunnel in terms of UI if we wanted.

I did use it recently and found it helpful, but not nearly as helpful as it was in the Elm days.

**Comment by pbiggar** [comment]
Closing as it doesn't apply to darklang-next
