### ISSUE TITLE
Expose SQLCompiler abilities of function in documentation

### ISSUE THREAD

**Issue by pbiggar** [darklang/dark#4728]

**Comment by OceanOak** [comment]
Could you please provide an example or direct me to where I can find more information?

**Comment by StachuDotNet** [comment]
Paul will likely fill in a bit more context, but in the meantime:

Each of our standard library functions (like `Int::mod`) has a `sqlSpec` property.
This property is used to figure out, if possible, how we should 'compile' the function to SQL for use in `DB::query` calls.

For example, `Int::mod` can be done in psql with an `%` and this is registered [here](https://github.com/darklang/dark/blob/04b343655017538d384c6e03ede4965670956094/backend/src/LibExecutionStdLib/LibInt.fs#L41).

The possible SqlSpec arrangements may be found [here](https://github.com/darklang/dark/blob/04b343655017538d384c6e03ede4965670956094/backend/src/LibExecution/RuntimeTypes.fs#L804-L833). Just below that, [here](https://github.com/darklang/dark/blob/main/backend/src/LibExecution/RuntimeTypes.fs#L804-L833) you can see that certain cases are considered 'queryable' and others are not.
(note: please don't like you need to review these links much - just for additional context if you're interested)

These properties are used in our [SqlCompiler](https://github.com/darklang/dark/blob/main/backend/src/LibBackend/SqlCompiler.fs) to 'compile' the DB queries from Dark to psql.

For example this is a legal query: 
  ![image](https://user-images.githubusercontent.com/906686/215550838-045996c0-662b-41eb-b4c4-b91be37e08f7.png)

but if I tried to do something non-sql-y like make an HTTP request in the middle of a `DB::query`, it won't work:
  ![image](https://user-images.githubusercontent.com/906686/215551091-f5a749e9-4831-4007-8c1b-2e54bcecaa2d.png)

The editor's autocomplete actively filters out httpclient fns from the list, since they're all marked as not queryable.

---

So, the definition of each of these functions includes its "sqlspec" - whether it's able to be compiled to psql or not - and the client/editor uses that currently to filter out many functions when writing a DB query.

What's _not_ done currently, is displaying whether a function is sql-compile-able in the UI anywhere.
We should show this information somewhere - maybe in the same area where we note "not deprecated."

Note: the types that I referenced before were our "backend" types - there's some translation that happens, and the types you should expect in the client are [here](https://github.com/darklang/dark/blob/04b343655017538d384c6e03ede4965670956094/client/src/core/RuntimeTypes.res#L546-L555).

**Comment by StachuDotNet** [comment]
I'm not sure about the UX of where we should best display this additional information. Worth some discussion I think

**Comment by StachuDotNet** [comment]
I'm guessing it's not super useful for Dark users to know how their Dark code will be compiled? At least, I'd only expect some indication of "this will work" or "this won't work"

**Comment by pbiggar** [comment]
> I'm guessing it's not super useful for Dark users to know how their Dark code will be compiled? At least, I'd only expect some indication of "this will work" or "this won't work" (in a DB::query)

It might be cool to say something like "this uses the postgres function `>`".

**Comment by pbiggar** [comment]
Closing as it doesn't apply to darklang-next
